const $ = (id)=>document.getElementById(id);
const STORAGE='at_ai_mobile_state_v2';
const BETS=[
  ['7li','7’li Ganyan'],['7plase','7’li Plase'],['3lu1','1. 3’lü Ganyan'],['3lu2','2. 3’lü Ganyan'],
  ['6li1','1. 6’lı Ganyan'],['6li2','2. 6’lı Ganyan'],['5li1','1. 5’li Ganyan'],['5li2','2. 5’li Ganyan'],['4lu','4’lü Ganyan']
];
let state={date:'',city:'',cities:[],races:[],analyses:{},tickets:[],view:'current'};
function todayLocal(){const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,10)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function restore(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(x)state={...state,...x}}catch{}}
function status(s){$('status').textContent=s}
function setupBets(){ $('betTypes').innerHTML=BETS.map(([id,n],i)=>`<label class="bet-card"><input type="checkbox" value="${id}" ${i<6?'checked':''}><span><strong>${n}</strong><span>Başlangıç koşusu TJK programından belirlenir</span></span></label>`).join('') }
function renderCities(){ $('citySelect').innerHTML=state.cities.length?state.cities.map(c=>`<option value="${c.id}" ${String(c.id)===String(state.city)?'selected':''}>${c.name}</option>`).join(''):'<option value="">Program yok</option>' }
function renderProgram(){
  const races=state.races||[];
  $('raceTabs').innerHTML=races.map(r=>`<button class="race-tab" data-race="${r.no}">${r.no}. Koşu</button>`).join('');
  $('raceList').classList.toggle('empty',!races.length);
  $('raceList').innerHTML=races.length?races.map(r=>`<article class="race-card" data-race-card="${r.no}"><div class="race-summary"><div><strong>${r.no}. Koşu ${r.time||''}</strong><div class="race-meta">${r.class||''} · ${r.distance||''} ${r.track||''}</div></div><div class="race-meta">${r.betStarts?.join(' · ')||''}</div></div><div class="horse-list">${(r.horses||[]).map(h=>`<div class="horse"><div class="horse-no">${h.no}</div><div><strong>${h.name}</strong><small>${h.jockey||''} · HP ${h.hp??'-'} · Gny ${h.odds??'-'}</small></div><div class="signal">${h.score?Math.round(h.score)+'%':''}</div></div>`).join('')}</div></article>`).join(''):'Program henüz yüklenmedi.';
  $('analysisRace').innerHTML='<option value="all">Tüm Koşular</option>'+races.map(r=>`<option value="${r.no}">${r.no}. Koşu</option>`).join('');
}
function renderTickets(){const t=state.tickets||[];$('tickets').classList.toggle('empty',!t.length);$('tickets').innerHTML=t.length?t.map(x=>`<div class="ticket"><strong>${x.name}</strong><div class="race-meta">Kaynak: ${x.sourceLabel} · ${x.created}</div><div class="legs">${x.legs.map(l=>`${l.race}. Koşu: <b>${l.horses.join('-')}</b>`).join('<br>')}</div></div>`).join(''):'Henüz kupon oluşturulmadı.'}
function syntheticScore(h,source){const seed=(Number(h.no)||1)*7+(Number(h.hp)||0)+(parseFloat(String(h.odds).replace(',','.'))||10);const factor={combined:1.0,current:.9,historical:.82,career:.86,manual:.7}[source]||.8;return Math.max(12,Math.min(96,Math.round((100-(seed%65))*factor+10)))}
function scoreRaces(source){state.races=state.races.map(r=>({...r,horses:r.horses.map(h=>({...h,score:syntheticScore(h,source)})).sort((a,b)=>b.score-a.score)}));save();renderProgram()}
function selectedBetIds(){return [...document.querySelectorAll('#betTypes input:checked')].map(x=>x.value)}
const LEN={ '7li':7,'7plase':7,'3lu1':3,'3lu2':3,'6li1':6,'6li2':6,'5li1':5,'5li2':5,'4lu':4 };
function betStart(id){const explicit=[];for(const r of state.races){for(const s of (r.betStarts||[])){if(s.toLowerCase().includes(BETS.find(b=>b[0]===id)?.[1].toLowerCase().replace('’','\'')))explicit.push(r.no)}}if(explicit.length)return explicit[0];const n=LEN[id]||1;if(id.endsWith('2'))return Math.max(1,state.races.length-n+1);return Math.max(1,state.races.length-n+1-(id.endsWith('1')?1:0))}
function buildTickets(source=$('signalSource').value){if(!state.races.length){status('Önce programı yükleyin.');return}scoreRaces(source);const singles=Number($('singleCount').value||0);const srcLabel=$('signalSource').selectedOptions[0]?.textContent||source;for(const id of selectedBetIds()){const len=LEN[id],start=betStart(id);const seq=state.races.filter(r=>r.no>=start).slice(0,len);const legs=seq.map((r,i)=>({race:r.no,horses:r.horses.slice(0,i<singles?1:Math.min(3,r.horses.length)).map(h=>h.no)}));state.tickets.unshift({id:crypto.randomUUID(),name:BETS.find(b=>b[0]===id)?.[1]||id,sourceLabel:srcLabel,created:new Date().toLocaleString('tr-TR'),legs})}save();renderTickets();status('Kuponlar oluşturuldu ve cihazda kaydedildi.')}
async function loadProgram(){const date=$('raceDate').value||todayLocal();status('TJK programı alınıyor…');try{const res=await fetch(`/api/tjk-program?date=${encodeURIComponent(date)}`);if(!res.ok)throw new Error('API '+res.status);const data=await res.json();state.date=date;state.cities=data.cities||[];state.city=state.city||state.cities[0]?.id||'';state.races=(data.racesByCity?.[state.city]||data.races||[]);save();renderCities();renderProgram();status(`${state.races.length} koşu yüklendi.`)}catch(e){status('TJK erişimi şu anda alınamadı. Uygulama yapısı hazır; API hatası: '+e.message)}}
function openDrawer(v=true){$('drawer').classList.toggle('open',v);$('overlay').classList.toggle('show',v)}
function openAnalysis(view){state.view=view;save();openDrawer(false);const names={current:'Güncel Analiz',historical:'Tarihsel Benzerlik',scenario:'Koşu Senaryosu',career:'Kariyer Yol Haritası'};$('dialogTitle').textContent=names[view]||'Analiz';$('dialogEyebrow').textContent=view==='career'?'4. BÖLÜM':'ANALİZ';$('analysisContent').innerHTML=state.analyses[view]?.html||'<div class="empty">Analizi Hesapla ile çalıştırın.</div>';$('analysisDialog').showModal()}
async function runAnalysis(){const raceNo=$('analysisRace').value;const races=raceNo==='all'?state.races:state.races.filter(r=>String(r.no)===String(raceNo));if(!races.length)return;const view=state.view;let html='';if(view==='career'){html='<div class="status">Tüm kariyerde ilk 5 bitirişler karşılaştırılıyor.</div>';for(const r of races){html+=`<div class="analysis-race"><strong>${r.no}. Koşu</strong>`;for(const h of r.horses.slice(0,8)){let road=[];try{const x=await fetch(`/api/tjk-career?horseId=${encodeURIComponent(h.id||'')}`);if(x.ok){const d=await x.json();road=(d.top5||[]).slice(0,12)}}catch{}const score=road.length?Math.min(98,35+road.filter(x=>x.finish===1).length*7+road.length*2):syntheticScore(h,'career');html+=`<div class="rank-row"><b>${h.no}</b><div><strong>${h.name}</strong><div class="roadmap">${road.length?road.map(x=>`<span class="pill ${x.finish===1?'win':''}">${x.date} · ${x.city||''} · ${x.finish}. · ${x.distance||''} ${x.track||''} · ${x.class||''}</span>`).join(''):'Kariyer kaydı API’den alınamadı; geçici skor kullanıldı.'}</div></div><b>${score}%</b></div>`}html+='</div>'}}
else{scoreRaces(view==='historical'?'historical':'current');html=races.map(r=>`<div class="analysis-race"><strong>${r.no}. Koşu</strong>${r.horses.slice(0,6).map(h=>`<div class="rank-row"><b>${h.no}</b><div>${h.name}<div class="roadmap">${view==='historical'?'Benzer geçmiş koşu sinyali':'Güncel yarış sinyali'}</div></div><b>${h.score}%</b></div>`).join('')}</div>`).join('')}
state.analyses[view]={html,at:Date.now()};save();$('analysisContent').innerHTML=html}
restore();setupBets();$('raceDate').value=state.date||todayLocal();renderCities();renderProgram();renderTickets();
$('loadProgramBtn').onclick=loadProgram;$('menuBtn').onclick=()=>openDrawer(true);$('closeMenu').onclick=()=>openDrawer(false);$('overlay').onclick=()=>openDrawer(false);document.querySelectorAll('.drawer [data-view]').forEach(b=>b.onclick=()=>openAnalysis(b.dataset.view));$('closeDialog').onclick=()=>$('analysisDialog').close();$('runAnalysis').onclick=runAnalysis;$('ticketFromAnalysis').onclick=()=>buildTickets(state.view==='career'?'career':state.view==='historical'?'historical':'current');$('buildAllBtn').onclick=()=>buildTickets();$('clearBtn').onclick=()=>{state.analyses={};state.tickets=[];save();renderTickets();status('Analizler ve kuponlar temizlendi. Program korunuyor.')};$('citySelect').onchange=async(e)=>{state.city=e.target.value;save();await loadProgram()};document.addEventListener('visibilitychange',()=>{if(!document.hidden){restore();renderCities();renderProgram();renderTickets()}});
