import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),runtime=path.join(root,'android/runtime'),target=path.join(root,'android/app/src/main/assets/node');
if(!fs.existsSync(path.join(runtime,'node_modules/cheerio')))throw Error('Önce npm ci --prefix android/runtime çalıştırın.');
fs.rmSync(target,{recursive:true,force:true});fs.mkdirSync(target,{recursive:true});
for(const name of ['server.mjs','package.json','android-filesystem.js'])fs.copyFileSync(path.join(runtime,name),path.join(target,name));
for(const [from,to]of [[path.join(root,'public'),'public'],[path.join(root,'api'),'api'],[path.join(runtime,'node_modules'),'node_modules']])fs.cpSync(from,path.join(target,to),{recursive:true});
for(const name of fs.readdirSync(path.join(target,'api'))){if(!name.endsWith('.js'))continue;const file=path.join(target,'api',name);let content=fs.readFileSync(file,'utf8');content=content.replace("from 'pdf-parse'","from 'pdf-parse/lib/pdf-parse.js'");content=content.replace(/(['"])https:\/\/at-ai-mobil\.vercel\.app\1/g,'process.env.AT_AI_LOCAL_API_BASE').replace(/(['"])at-ai-mobil\.vercel\.app\1/g,"new URL(process.env.AT_AI_LOCAL_API_BASE).host");fs.writeFileSync(file,content)}
fs.copyFileSync(path.join(root,'universal-v5-prototype-v165.js'),path.join(target,'universal-v5-prototype-v165.js'));
const indexFile=path.join(target,'public/index.html');let index=fs.readFileSync(indexFile,'utf8');index=index.replace('<head>','<head>\n<script src="/android-filesystem.js"></script>');fs.writeFileSync(indexFile,index);fs.copyFileSync(path.join(runtime,'android-filesystem.js'),path.join(target,'public/android-filesystem.js'));
const dirFile=path.join(target,'public/at-ai-app-v142.js');let app=fs.readFileSync(dirFile,'utf8');for(const item of JSON.parse(fs.readFileSync(path.join(root,'android/vendor-manifest.json'),'utf8')))app=app.split(item.url).join('/vendor/'+item.name);fs.cpSync(path.join(root,'android/vendor'),path.join(target,'public/vendor'),{recursive:true});app=app.replace('async function storedHandle(){','async function storedHandle(){if(window.ATAndroidArchive)return window.ATAndroidArchive.restoreRoot();').replace('async function remember(h){','async function remember(h){if(window.ATAndroidArchive)return window.ATAndroidArchive.rememberRoot(h);');fs.writeFileSync(dirFile,app);
const digest=crypto.createHash('sha256');function hashTree(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const file=path.join(dir,item.name);if(item.isDirectory())hashTree(file);else if(item.name!=='bundle-version.txt'){digest.update(path.relative(target,file));digest.update(fs.readFileSync(file))}}}hashTree(target);fs.writeFileSync(path.join(target,'bundle-version.txt'),digest.digest('hex'));console.log('Android payload hazır.');
