import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function runtime(actualKey){
 const reads=[],stores=new Map(),actual={key:actualKey,date:'2026-10-01',city:'Kocaeli',raceNo:1,race:{rows:[{programNo:1,horseName:'AT 1',finish:1,degree:'1.38.00'}]}};
 const prediction={key:'2026-10-01|KOCAELI|1',date:'2026-10-01',city:'Kocaeli',raceNo:1,year:2026,schema:1744,eligibleForCalibration:true,locked:true,trackContext:{surface:'KUM'},horses:[{no:1,name:'AT 1',predictedSec:100,uncalibratedSec:100,rank:1}]};
 stores.set('at_ai_tjk_annual_results_v1',new Map([[actualKey,actual]]));stores.set('at_ai_degree_predictions_v1',new Map([[prediction.key,prediction]]));
 const indexedDB={open(name){const q={};queueMicrotask(()=>{if(!stores.has(name))stores.set(name,new Map());const data=stores.get(name);q.result={objectStoreNames:{contains:()=>true},close(){},transaction(){const tx={objectStore(){return{get(k){reads.push([name,'get',k]);const r={};queueMicrotask(()=>{r.result=data.get(k);r.onsuccess?.()});return r},getAll(){reads.push([name,'getAll']);const r={};queueMicrotask(()=>{r.result=[...data.values()];r.onsuccess?.()});return r},put(v){data.set(v.key,v)},clear(){data.clear()}}}};setImmediate(()=>tx.oncomplete?.());return tx}};q.onsuccess?.()});return q}};
 const window={addEventListener(){}};vm.runInNewContext(fs.readFileSync(new URL('../degree-calibration-v1744.js',import.meta.url),'utf8'),{window,indexedDB,document:{readyState:'loading',addEventListener(){}},console,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,queueMicrotask,Intl,Date});return{api:window.ATDegreeCalibrationV1744,reads,stores,prediction};
}
for(const prefix of ['result|',''])test(`calibration joins targeted ${prefix||'legacy'} result keys without loading the result archive`,async()=>{const r=runtime(prefix+'2026-10-01|KOCAELI|1');const samples=await r.api.rebuildSamples();assert.equal(samples.length,1);assert.equal(samples[0].rawErrorSec,-2);assert.equal(r.reads.some(([db,op])=>db==='at_ai_tjk_annual_results_v1'&&op==='getAll'),false)});
test('targeted result lookup still prevents a finished race becoming training data',async()=>{const r=runtime('result|2026-10-01|KOCAELI|1');r.stores.get('at_ai_degree_predictions_v1').clear();const saved=await r.api.capture({date:'2026-10-01',cityName:'Kocaeli',degreeSpeed:{calculationVersion:'DEGREE-STABLE-INPUTS-V17.4.4'},races:[{no:1,horses:[{no:1,name:'AT 1',degreeModel:{predictedSec:100,rank:1}}]}]},{date:'2026-10-01',city:'Kocaeli',now:new Date('2026-09-30T12:00:00Z'),programRaces:[{no:1,track:'Kum',time:'18:00'}]});assert.equal(saved[0].eligibleForCalibration,false);assert.equal(saved[0].locked,false);assert.equal(r.reads.some(([db,op])=>db==='at_ai_tjk_annual_results_v1'&&op==='getAll'),false)});

test('a query winner summary also marks the race finished without full runner results',async()=>{const r=runtime('result|2026-10-01|KOCAELI|1');const actual=r.stores.get('at_ai_tjk_annual_results_v1').values().next().value;actual.race.rows=[];actual.referenceQuery={winnerDegree:'1.38.00'};r.stores.get('at_ai_degree_predictions_v1').clear();const saved=await r.api.capture({date:'2026-10-01',cityName:'Kocaeli',degreeSpeed:{calculationVersion:'DEGREE-STABLE-INPUTS-V17.4.4'},races:[{no:1,horses:[{no:1,name:'AT 1',degreeModel:{predictedSec:100,rank:1}}]}]},{date:'2026-10-01',city:'Kocaeli',now:new Date('2026-09-30T12:00:00Z'),programRaces:[{no:1,track:'Kum',time:'18:00'}]});assert.equal(saved[0].eligibleForCalibration,false);assert.equal(saved[0].locked,false)});
