import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {parseRows} from '../api/tjk-race-query-v1.js';
const window={addEventListener(){}};vm.runInNewContext(fs.readFileSync(new URL('../reference-archive-v17412.js',import.meta.url),'utf8'),{window,Date,setTimeout,clearTimeout});const api=window.ATReferenceArchiveV17412;
const row={date:'2026-09-30',city:'Kocaeli',raceNo:1,group:'3 Yaşlı Araplar',raceType:'Handikap 14 /DHÖ /Dişi /H2',distance:1400,track:'Kum',winner:'AT 1',winnerDegree:'1.36.96'};
const job={start:'2026-09-29',end:'2026-09-30',cursor:'2026-09-29',windowEnd:'2026-09-30',page:0,processed:0,total:0,pageSize:0,seen:0,fingerprints:[]};
test('TJK common CSS prefix cannot turn a date into a race number or winner into age',()=>{const p=parseRows(fs.readFileSync(new URL('fixtures/race-query-columns.html',import.meta.url),'utf8'));assert.deepEqual(p.rows.map(r=>r.raceNo),[1,2]);assert.equal(p.rows[0].winner,'EUROFIGHTER');assert.equal(p.rows[0].age,'3y d e');assert.equal(p.rows[0].hp,48);assert.equal(new Set(p.rows.map(r=>r.key)).size,2)});
test('query summaries use the exact store schema consumed by the degree history model',()=>{const r=api.normalize(row);assert.equal(r.key,'result|2026-09-30|KOCAELI|1');assert.equal(r.race.winner.degree,'1.36.96');assert.equal(r.race.ageGroup,row.group);assert.equal(r.race.class,row.raceType);assert.equal(r.referenceOnly,true);assert.equal(r.race.rows.length,0);assert.throws(()=>api.normalize({...row,raceNo:30.09}));assert.throws(()=>api.normalize({...row,winnerDegree:''}))});
test('importing references preserves existing full results and actual finish data',()=>{const old={key:'old',race:{rows:[{horseName:'AT 1',finish:1}],winner:{degree:'1.36.96'},class:'Handikap 14'}};const merged=api.mergeRecord(old,api.normalize(row));assert.deepEqual(merged.race.rows,old.race.rows);assert.equal(merged.race.class,old.race.class);assert.equal(merged.referenceOnly,false);assert.equal(merged.referenceQuery.winner,row.winner)});
test('page checkpoint advances only with complete distinct and in-range rows',()=>{const a=api.advance(job,{rows:[row],total:2,rawRowCount:1});assert.equal(a.next.page,1);assert.equal(a.next.cursor,job.cursor);assert.throws(()=>api.advance(a.next,{rows:[row],total:2}),/aynı sayfayı/);assert.throws(()=>api.advance(a.next,{rows:[],total:2}),/boş/);assert.throws(()=>api.advance(job,{rows:[row,row],total:2}),/tekrar/);assert.throws(()=>api.advance(job,{rows:[{...row,date:'2026-10-01'}],total:1}),/dışında/);const b=api.advance(a.next,{rows:[{...row,raceNo:2}],total:2,rawRowCount:1});assert.equal(b.next.status,'complete');assert.equal(b.next.processed,2)});
test('free date ranges are validated without fixed historical limits',()=>{assert.equal(api.validRange('2007-02-11','2026-09-30'),true);assert.equal(api.validRange('2026-02-30','2026-03-01'),false);assert.equal(api.validRange('2026-10-01','2026-09-30'),false)});
