import * as cheerio from 'cheerio';

const TJK='https://www.tjk.org';
const VERSION='TJK-HISTORY-V1.2-MARGIN';
const TIMEOUT_MS=18000;
const CONCURRENCY=3;
const DEFAULT_MAX_ROWS=6;
const HARD_MAX_ROWS=30;
const HEADERS={
  'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/150 Safari/537.36',
  accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language':'tr-TR,tr;q=0.9,en;q=0.7',
  referer:'https://www.tjk.org/',
  'cache-control':'no-cache'
};
function clean(v=''){return String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim()}
function upper(v=''){return clean(v).toLocaleUpperCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'')}
function normalizeName(v=''){return upper(v).replace(/[^A-Z0-9]+/g,'')}
function isoToDisplay(iso=''){const m=clean(iso).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:''}
function normalizeTrack(v=''){const t=upper(v);if(t.includes('CIM'))return'Çim';if(t.includes('KUM'))return'Kum';if(t.includes('SENTETIK'))return'Sentetik';return''}
function marginLengths(raw=''){
  const t=upper(raw).replace(/,/g,'.').replace(/\s+/g,' ').trim();
  if(!t)return null;if(t.includes('ATBASI')||t.includes('AT BASI'))return 0;if(t.includes('BURUN'))return.05;if(/\bBAS\b/.test(t))return.10;if(t.includes('BOYUN'))return.25;if(t.includes('YARIM'))return.50;if(/\b1\s*\/\s*2\s*BOY\b/.test(t))return.50;if(/\b3\s*\/\s*4\s*BOY\b/.test(t))return.75;
  const mixed=t.match(/(\d+)\s+(1\s*\/\s*2)\s*BOY/);if(mixed)return Number(mixed[1])+.5;
  const m=t.match(/(\d+(?:\.\d+)?)\s*BOY/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)?n:null;
}
function closeLabel(gap){if(!Number.isFinite(gap))return null;if(gap<=.10)return'ÇOK YAKIN';if(gap<=.50)return'YAKIN';if(gap<=1)return'YAKIN MÜCADELE';if(gap<=2)return'TEMASLI';return'AÇIK FARK'}
async function fetchHtml(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:HEADERS,redirect:'follow',signal:c.signal});if(!r.ok)throw new Error(`TJK HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function getHeaders($,table){let h=$(table).find('thead th').map((_,x)=>clean($(x).text())).get();if(!h.length)h=$(table).find('tr').first().find('th,td').map((_,x)=>clean($(x).text())).get();return h}
function findHeader(h,re){return h.findIndex(x=>re.test(clean(x)))}
async function findCityResultUrl(dateIso,cityName){const d=isoToDisplay(dateIso);if(!d)throw new Error('Geçersiz tarih.');const html=await fetchHtml(`${TJK}/TR/YarisSever/Info/Page/GunlukYarisSonuclari?QueryParameter_Tarih=${encodeURIComponent(d)}`),$=cheerio.load(html),target=upper(cityName);let found='';$('a').each((_,a)=>{if(found)return;const text=upper($(a).text()),href=String($(a).attr('href')||'');if(href.includes('GunlukYarisSonuclari')&&text.startsWith(target))found=new URL(href,TJK).toString()});if(!found)throw new Error(`${cityName} için ${dateIso} tarihli TJK yarış sonucu bulunamadı.`);return found}
function parseCondition(value=''){const text=clean(value),parts=text.split(',').map(clean).filter(Boolean),dm=text.match(/\b(\d{3,4})\s+(?:Çim|Kum|Sentetik)\b/i);return{class:parts[0]||'',ageGroup:parts[1]||'',distance:dm?`${dm[1]}m`:'',track:normalizeTrack(text),raw:text}}
function parseHorseCell($,cell){const first=$(cell).find('a').first(),linkText=clean(first.text()),text=clean($(cell).text()),horseText=linkText||text,pm=horseText.match(/\((\d+)\)/);let name=horseText.replace(/\(\d+\).*$/,'').trim();if(!linkText)name=name.replace(/\s+(KG|K|DB|SK|SKG|YP|ÖG|GKR|BB).*$/i,'').trim();let horseId='';$(cell).find('a').each((_,a)=>{if(horseId)return;const m=String($(a).attr('href')||'').match(/QueryParameter_AtId=(-?\d+)/i);if(m)horseId=String(m[1]).replace(/\D/g,'')});return{id:horseId,name,programNo:pm?Number(pm[1]):null}}
function addWinnerGaps(rows){rows.sort((a,b)=>a.finish-b.finish);for(const row of rows){if(row.finish===1){row.winnerGapApprox=0;row.winnerGapChain='0'}else{const prev=rows.filter(x=>x.finish<row.finish),nums=prev.map(x=>x.marginToNextApprox),chain=prev.map(x=>x.marginRaw).filter(Boolean);row.winnerGapApprox=nums.length===row.finish-1&&nums.every(Number.isFinite)?nums.reduce((a,b)=>a+b,0):null;row.winnerGapChain=chain.join(' + ')||null}row.closeFinish=Number.isFinite(row.winnerGapApprox)?row.winnerGapApprox<=1:null;row.closeFinishLabel=closeLabel(row.winnerGapApprox)}return rows}
function parseResultPage(html,requestedRaceNo){const $=cheerio.load(html);let activeRaceNo=null,activeCondition='',result=null;$('h3, table').each((_,el)=>{if(result)return;const tag=String(el.tagName||el.name||'').toLowerCase();if(tag==='h3'){const text=clean($(el).text()),rm=text.match(/^(\d+)\.\s*Koşu\b/i);if(rm){activeRaceNo=Number(rm[1]);activeCondition='';return}if(activeRaceNo&&!activeCondition&&/(?:Kum|Çim|Sentetik)/i.test(text))activeCondition=text;return}if(tag!=='table'||Number(activeRaceNo)!==Number(requestedRaceNo))return;const h=getHeaders($,el),finishIx=findHeader(h,/^S$/i),horseIx=findHeader(h,/At İsmi|At Ismi/i),marginIx=findHeader(h,/^Fark$/i);if(finishIx<0||horseIx<0)return;const top5=[];$(el).find('tbody tr').each((_,tr)=>{const cells=$(tr).find('td').toArray();if(cells.length<=Math.max(finishIx,horseIx))return;const fm=clean($(cells[finishIx]).text()).match(/\d+/);if(!fm)return;const finish=Number(fm[0]);if(finish<1||finish>5)return;const horse=parseHorseCell($,cells[horseIx]),marginRaw=marginIx>=0&&cells.length>marginIx?(clean($(cells[marginIx]).text())||null):null;top5.push({finish,horseId:horse.id,horseName:horse.name,programNo:horse.programNo,margin:marginRaw,marginRaw,marginToNextApprox:marginLengths(marginRaw)})});if(top5.length)result={raceNo:activeRaceNo,condition:parseCondition(activeCondition),top5:addWinnerGaps(top5)}});return result}
function parseRaceNo(row={}){const raw=clean(row.raceNo??row.race_no??row.raceNoName??row.kosu_no_adi??row.kosuNo??'');const m=raw.match(/\d+/);return m?Number(m[0]):0}
function parseFinish(row={}){const n=Number(row.finish??row.rank??row.sira);return Number.isFinite(n)?Math.trunc(n):0}
async function mapLimit(items,limit,worker){const list=Array.isArray(items)?items:[],out=new Array(list.length);let cursor=0;async function run(){while(true){const i=cursor++;if(i>=list.length)return;out[i]=await worker(list[i],i)}}await Promise.all(Array.from({length:Math.min(Math.max(1,limit),list.length||1)},()=>run()));return out}
async function resolveMarginRow(row){const date=clean(row.isoDate||row.date),city=clean(row.city||row.sehir),raceNo=parseRaceNo(row),finish=parseFinish(row);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!city||!raceNo||finish<1||finish>5)return null;const resultUrl=await findCityResultUrl(date,city),race=parseResultPage(await fetchHtml(resultUrl),raceNo);if(!race)throw new Error('Koşu sonucu ayrıştırılamadı.');const rows=race.top5||[],horseId=clean(row.horseId||row.atId||row.id),horseName=normalizeName(row.horseName||row.atAdi||row.name);let hit=horseId?rows.find(x=>clean(x.horseId)===horseId):null;if(!hit&&horseName)hit=rows.find(x=>normalizeName(x.horseName)===horseName);if(!hit)hit=rows.find(x=>x.finish===finish)||null;if(!hit)throw new Error('At sonuç satırında eşleştirilemedi.');return{uniqueKey:clean(row.uniqueKey),isoDate:date,city,raceNo,marginRawToNext:hit.marginRaw,marginToNextApprox:hit.marginToNextApprox,winnerGapApprox:hit.winnerGapApprox,winnerGapChain:hit.winnerGapChain,closeFinish:hit.closeFinish,closeFinishLabel:hit.closeFinishLabel,marginSource:'TJK_GUNLUK_YARIS_SONUCLARI',resultUrl}}
async function handlePost(req,res){let body=req.body;if(typeof body==='string')body=JSON.parse(body||'{}');const history=Array.isArray(body?.history)?body.history:[],requested=Number(body?.maxRows),maxRows=Math.max(1,Math.min(HARD_MAX_ROWS,Number.isFinite(requested)?Math.trunc(requested):DEFAULT_MAX_ROWS));const candidates=history.filter(r=>{const f=parseFinish(r);return f>=1&&f<=5&&parseRaceNo(r)>0&&/^\d{4}-\d{2}-\d{2}$/.test(clean(r.isoDate||r.date))&&clean(r.city||r.sehir)}).sort((a,b)=>clean(b.isoDate||b.date).localeCompare(clean(a.isoDate||a.date))).slice(0,maxRows);const resolved=await mapLimit(candidates,CONCURRENCY,async row=>{try{return{ok:true,data:await resolveMarginRow(row)}}catch(e){return{ok:false,uniqueKey:clean(row.uniqueKey),isoDate:clean(row.isoDate||row.date),error:e?.message||String(e)}}});const margins=resolved.filter(x=>x?.ok&&x.data).map(x=>x.data),errors=resolved.filter(x=>x&&!x.ok).map(x=>({uniqueKey:x.uniqueKey,isoDate:x.isoDate,error:x.error}));res.setHeader('Cache-Control','no-store');return res.status(200).json({ok:true,version:VERSION,mode:'MARGIN_ENRICH',requestedRows:history.length,eligibleRows:candidates.length,maxRows,enrichedRows:margins.length,errorRows:errors.length,margins,errors,rule:'İlk 5 için TJK Fark zinciri kümülatif toplanarak kazanana yaklaşık boy farkı hesaplanır.',closeRule:'Kazanana yaklaşık fark <= 1 boy ise yakın mücadele.'})}
async function handleGet(req,res){const date=clean(req.query.date||''),city=clean(req.query.city||''),raceNo=Number(req.query.raceNo||0);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({ok:false,error:'date YYYY-MM-DD biçiminde gerekli.'});if(!city)return res.status(400).json({ok:false,error:'city gerekli.'});if(!Number.isInteger(raceNo)||raceNo<1)return res.status(400).json({ok:false,error:'raceNo gerekli.'});const resultUrl=await findCityResultUrl(date,city),race=parseResultPage(await fetchHtml(resultUrl),raceNo);if(!race)return res.status(404).json({ok:false,error:`${date} ${city} ${raceNo}. koşu sonucu bulunamadı.`,resultUrl});const top3=(race.top5||[]).filter(x=>x.finish<=3),missingHorseIds=top3.filter(x=>!x.horseId).length;res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');return res.status(200).json({ok:true,version:VERSION,date,city,raceNo,class:race.condition.class,ageGroup:race.condition.ageGroup,distance:race.condition.distance,track:race.condition.track,conditionRaw:race.condition.raw,top3,top5:race.top5,top3Count:top3.length,top5Count:race.top5.length,horseIdsComplete:missingHorseIds===0,missingHorseIds,marginRule:'Fark, bir sonraki ata olan farktır; kazanana fark önceki Fark değerlerinin kümülatif toplamıdır.',source:'TJK_GUNLUK_YARIS_SONUCLARI'})}
export default async function handler(req,res){try{if(req.method==='POST')return await handlePost(req,res);if(req.method==='GET'||!req.method)return await handleGet(req,res);return res.status(405).json({ok:false,error:'GET veya POST gerekli.'})}catch(e){console.error('tjk-history:',e);return res.status(500).json({ok:false,version:VERSION,error:e?.message||'Tarihsel yarış sonucu alınamadı.'})}}
